<script lang="ts">
  import BrandingLogo from "$components/branding/BrandingLogo.svelte";
  import { Button } from "$ui/button";
  import { ImageIcon, Download, QrCode, Share2, ShieldCheck } from "@lucide/svelte";
  import { Spinner } from "$ui/spinner";
  import { brandingState } from "$state/branding.svelte";
  import { formatDate } from "$utils/formatters";
  import { normalizeStudentNo } from "$utils/student-no";
  import { translatePeriod } from "$utils/translators";

  interface Props {
    clearanceData: {
      name: string;
      stno: string;
      period: string;
      dateIssued: string;
      refNo: string;
      branding: string;
      signatory: string;
      signatoryTitle: string;
    };
    qrDataUrl: string;
    isExporting: boolean;
    onDownloadPDF: () => void;
    onDownloadImage: () => void;
    onShareLink: () => void;
    onShareQR: () => void;
  }

  let {
    clearanceData,
    qrDataUrl,
    isExporting,
    onDownloadPDF,
    onDownloadImage,
    onShareLink,
    onShareQR
  }: Props = $props();

  const activeBranding = $derived(brandingState.profile);

  let clickedAction = $state<string | null>(null);

  $effect(() => {
    if (!isExporting) {
      clickedAction = null;
    }
  });

  function handleAction(type: string, callback: () => void) {
    clickedAction = type;
    callback();
  }

  const clearanceDetails = $derived([
    { label: "Date Issued", value: formatDate(clearanceData.dateIssued) },
    { label: "Student Number", value: normalizeStudentNo(clearanceData.stno), mono: true },
    { label: "Reference Number", value: clearanceData.refNo, mono: true }
  ]);
</script>

<!-- SNIPPETS -->
{#snippet ticketHeader()}
  <div class="ticket-header-notch rounded-t-3xl bg-card pb-5 text-card-foreground">
    <div class="flex flex-col items-center px-7 pt-8 text-center">
      <!-- Shield Check Badge Icon -->
      <div class="relative mb-4 flex items-center justify-center">
        <div
          class="flex h-16 w-16 items-center justify-center rounded-full bg-brand text-brand-foreground"
        >
          <ShieldCheck class="h-8 w-8 stroke-3" />
        </div>
      </div>

      <!-- Title & Subtitle -->
      <h2 class="text-2xl font-bold tracking-tight">Certificate of Full Payment</h2>
      <p class="mt-1 text-sm text-muted-foreground">
        Issued by the {activeBranding.issuerName}
      </p>

      <!-- Cleared Resident Banner -->
      <div class="mt-6 flex flex-col items-center">
        <span class="text-xs font-semibold tracking-wider text-muted-foreground uppercase">
          Resident
        </span>
        <span class="mt-1 text-center font-sans text-2xl font-extrabold tracking-tight sm:text-3xl">
          {clearanceData.name}
        </span>
      </div>
    </div>
  </div>
{/snippet}

{#snippet ticketDivider()}
  <div class="relative z-10 -my-px flex items-center justify-between">
    <div class="mx-7 w-full border-t-2 border-dashed border-border/80"></div>
  </div>
{/snippet}

{#snippet certificationStatement()}
  <div class="space-y-4 text-sm">
    <div class="space-y-3 rounded-2xl bg-muted p-4">
      <p class="text-justify leading-relaxed">
        This certifies that <span class="font-bold">{clearanceData.name}</span>
        has been cleared of any liability regarding association and water fees for the
        <span class="font-bold">{translatePeriod(clearanceData.period)}</span>.
      </p>

      <div class="flex flex-col items-center pt-2 text-center text-sm">
        <span class="font-bold uppercase">{clearanceData.signatory}</span>
        <span class="font-medium text-muted-foreground">{clearanceData.signatoryTitle}</span>
      </div>
    </div>
  </div>
{/snippet}

{#snippet metadataSection()}
  <div class="space-y-4 text-sm">
    <!-- Metadata Rows -->
    <div class="space-y-2 px-0.5 text-sm">
      {#each clearanceDetails as detail}
        <div
          class="flex flex-col justify-between border-b border-border/40 py-1.5 md:flex-row md:items-center"
        >
          <span class="text-muted-foreground">{detail.label}</span>
          <span class="font-medium md:text-right {detail.mono ? 'font-mono text-xs' : ''}">
            {detail.value}
          </span>
        </div>
      {/each}
    </div>

    <!-- Bottom HA1 & QR Info -->
    <div class="flex items-center justify-between pt-1 pb-1">
      <div class="flex items-center gap-2">
        <img src="/ha1.svg" alt="HA1 Logo" class="h-6 w-auto opacity-50 contrast-125 grayscale" />
        <div class="text-xs leading-tight text-muted-foreground">
          <span>Generated by HAOne v{__APP_VERSION__}</span>
        </div>
      </div>
      {#if qrDataUrl}
        <img src={qrDataUrl} alt="Verification QR" class="h-16 w-16" />
      {/if}
    </div>
  </div>
{/snippet}

{#snippet scallopedBottom()}
  <div class="ticket-scallop -mt-px h-4 w-full bg-card"></div>
{/snippet}

{#snippet actionButtons()}
  <div class="mt-6 space-y-2.5">
    <!-- Primary Export Action -->
    <Button
      onclick={() => handleAction("pdf", onDownloadPDF)}
      size="lg"
      class="h-12 w-full bg-brand font-bold text-brand-foreground hover:bg-brand/90"
      disabled={isExporting}
      icon={isExporting && clickedAction === "pdf" ? Spinner : Download}
    >
      Export PDF
    </Button>

    <!-- Secondary Actions Bar -->
    <div class="grid grid-cols-3 gap-2">
      <Button
        onclick={() => handleAction("image", onDownloadImage)}
        size="sm"
        variant="secondary"
        disabled={isExporting}
        icon={isExporting && clickedAction === "image" ? Spinner : ImageIcon}
      >
        Save Image
      </Button>
      <Button
        onclick={() => handleAction("qr", onShareQR)}
        size="sm"
        variant="secondary"
        disabled={isExporting}
        icon={isExporting && clickedAction === "qr" ? Spinner : QrCode}
      >
        Share QR
      </Button>
      <Button
        onclick={() => handleAction("link", onShareLink)}
        size="sm"
        variant="secondary"
        disabled={isExporting}
        icon={isExporting && clickedAction === "link" ? Spinner : Share2}
      >
        Share Link
      </Button>
    </div>
  </div>
{/snippet}

<div class="mx-auto w-full max-w-md print:hidden">
  <!-- TOP BRAND TITLE -->
  <div class="mb-5 flex justify-center">
    <BrandingLogo class="h-16 w-auto object-contain" />
  </div>

  <!-- TICKET CARD CONTAINER -->
  <div class="relative drop-shadow-sm">
    {@render ticketHeader()}
    {@render ticketDivider()}

    <!-- BOTTOM CARD SECTION -->
    <div class="ticket-body-notch bg-card pt-5 text-card-foreground">
      <div class="space-y-4 px-7 pb-6">
        {@render certificationStatement()}
        {@render metadataSection()}
      </div>
    </div>

    {@render scallopedBottom()}
  </div>

  {@render actionButtons()}
</div>

<style>
  .ticket-header-notch {
    mask-image:
      radial-gradient(circle at 0px 100%, transparent 16px, black 16.5px),
      radial-gradient(circle at 100% 100%, transparent 16px, black 16.5px);
    mask-composite: intersect;
    -webkit-mask-image:
      radial-gradient(circle at 0px 100%, transparent 16px, black 16.5px),
      radial-gradient(circle at 100% 100%, transparent 16px, black 16.5px);
    -webkit-mask-composite: source-in;
  }

  .ticket-body-notch {
    mask-image:
      radial-gradient(circle at 0px 0px, transparent 16px, black 16.5px),
      radial-gradient(circle at 100% 0px, transparent 16px, black 16.5px);
    mask-composite: intersect;
    -webkit-mask-image:
      radial-gradient(circle at 0px 0px, transparent 16px, black 16.5px),
      radial-gradient(circle at 100% 0px, transparent 16px, black 16.5px);
    -webkit-mask-composite: source-in;
  }

  .ticket-scallop {
    mask-image: radial-gradient(circle at 14px 16px, transparent 10px, black 10.5px);
    mask-size: 28px 16px;
    mask-repeat: round no-repeat;
    -webkit-mask-image: radial-gradient(circle at 14px 16px, transparent 10px, black 10.5px);
    -webkit-mask-size: 28px 16px;
    -webkit-mask-repeat: round no-repeat;
  }
</style>
